export const CLIENT_REGISTER_FAILED = "CLIENT_REGISTER_FAILED";
export const CLIENT_REGISTER_REQUEST = "CLIENT_REGISTER_REQUEST";
export const CLIENT_REGISTER_SUCCESS = "CLIENT_REGISTER_SUCCESS";

export const CLIENT_DETAILS_REQUEST = "CLIENT_DETAILS_REQUEST";
export const CLIENT_DETAILS_FAILED = "CLIENT_DETAILS_FAILED";
export const CLIENT_DETAILS_SUCCESS = "CLIENT_DETAILS_SUCCESS";