export const LINK_NEW_CLIENT    = "/client"        
export const LINK_NEW_PROJECT   = "/project"        
export const LINK_NEW_PHASE     = "/phase/:id"        
export const LINK_PHASES     = "/phases/:id"        
export const LINK_NEW_USER      = "/user"        
