
export const PROJECT_LIST_FAILED = "PROJECT_LIST_FAILED";
export const PROJECT_LIST_REQUEST = "PROJECT_LIST_REQUEST";
export const PROJECT_LIST_SUCCESS = "PROJECT_LIST_SUCCESS";

export const PROJECT_REGISTER_FAILED = "PROJECT_REGISTER_FAILED";
export const PROJECT_REGISTER_REQUEST = "PROJECT_REGISTER_REQUEST";
export const PROJECT_REGISTER_SUCCESS = "PROJECT_REGISTER_SUCCESS";