
export const PROJECT_LIST_FAILED = "PROJECT_LIST_FAILED";
export const PROJECT_LIST_REQUEST = "PROJECT_LIST_REQUEST";
export const PROJECT_LIST_SUCCESS = "PROJECT_LIST_SUCCESS";

export const PROJECT_REGISTER_FAILED = "PROJECT_REGISTER_FAILED";
export const PROJECT_REGISTER_REQUEST = "PROJECT_REGISTER_REQUEST";
export const PROJECT_REGISTER_SUCCESS = "PROJECT_REGISTER_SUCCESS";

export const PROJECT_DETAILS_FAILED = "PROJECT_DETAILS_FAILED";
export const PROJECT_DETAILS_REQUEST = "PROJECT_DETAILS_REQUEST";
export const PROJECT_DETAILS_SUCCESS = "PROJECT_DETAILS_SUCCESS";

export const PROJECT_UPDATE_PROFILE_REQUEST = "PROJECT_UPDATE_PROFILE_REQUEST";
export const PROJECT_UPDATE_PROFILE_FAILED = "PROJECT_UPDATE_PROFILE_FAILED";
export const PROJECT_UPDATE_PROFILE_SUCCESS = "PROJECT_UPDATE_PROFILE_SUCCESS";
export const PROJECT_UPDATE_PROFILE_RESET = "PROJECT_UPDATE_PROFILE_RESET";