export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAILED = "USER_LOGIN_FAILED";

export const USER_LOGOUT_SUCCESS = "USER_LOGOUT_SUCCESS";
export const USER_LOGOUT_FAILED = "USER_LOGOUT_FAILED";

export const USER_LIST_REQUEST = "USER_LIST_REQUEST";
export const USER_LIST_SUCCESS = "USER_LIST_SUCCESS";
export const USER_LIST_FAILED = "USER_LIST_FAILED";

export const USER_REGISTER_REQUEST = "USER_REGISTER_REQUEST";
export const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS";
export const USER_REGISTER_FAILED = "USER_REGISTER_FAILED";

export const CLIENT_REGISTER_REQUEST = "CLIENT_REGISTER_REQUEST";
export const CLIENT_REGISTER_SUCCESS = "CLIENT_REGISTER_SUCCESS";
export const CLIENT_REGISTER_FAILED = "CLIENT_REGISTER_FAILED";

export const PROJECT_REGISTER_REQUEST = "PROJECT_REGISTER_REQUEST";
export const PROJECT_REGISTER_SUCCESS = "PROJECT_REGISTER_SUCCESS";
export const PROJECT_REGISTER_FAILED = "PROJECT_REGISTER_FAILED";

export const USER_DETAILS_FAILED = "USER_DETAILS_FAILED";
export const USER_DETAILS_REQUEST = "USER_DETAILS_REQUEST"
export const USER_DETAILS_SUCCESS = "USER_DETAILS_SUCCESS"

export const USER_UPDATE_PROFILE_FAILED = "USER_UPDATE_PROFILE_FAILED";
export const USER_UPDATE_PROFILE_REQUEST = "USER_UPDATE_PROFILE_REQUEST";
export const USER_UPDATE_PROFILE_SUCCESS = "USER_UPDATE_PROFILE_SUCCESS";

export const USER_DELETE_REQUEST = "USER_DELETE_REQUEST"
export const USER_DELETE_FAILED  = "USER_DELETE_FAILED"
export const USER_DELETE_SUCCESS = "USER_DELETE_SUCCESS"